apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.evaluation.finished
      requests:
        - "curl --header 'Content-type: application/json' --header
          'Authorization: Bearer
          xoxb-622401658016-672262788135-fJofsYJsjUugfYyUvcDhnhjs' --request
          POST --data
          '{\"channel\":\"TJABTKC0G/C02EE5TREKB\",\"text\":\"{{.data.project}}
          has {{.data.evaluation.result}} with
          score{{.data.evaluation.score}}\"}'
          https://slack.com/api/chat.postMessage"
      subscriptionID: c9889924-1661-4780-9e78-16d5ba55f57e
      sendFinished: false
