apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.evaluation.finished
      requests:
        - "curl --header 'accept: application/json' --header 'Authorization:
          Api-Token
          dt0c01.TQWVIRNEZLWG2XVJ4BY5WC3W.UHRZSB6GXPBQI2Z54Z37NQDYJT5SPBFLRTSFL\
          BNIAM6ODB4LADSRHSGSTXRJDIJH' --header 'Content-Type: application/json'
          --request POST --data '{  \"type\": \"test\",  \"series\":
          [    {      \"timeseriesId\":
          \"custom:releaseevaluationscore\",      \"dimensions\":
          {        \"Score\" : {{.data.evaluation.score}},        \"Result\" :
          \"{{.data.result}}\",        \"Passed\" :
          0,        \"Releaseversion\":
          \"{{.data.labels.buildId}}\",        \"Buildversion\":
          \"{{.data.labels.buildId}}\",        \"Buildnumber\": 001
          ,        \"Evaluationtime\": \"{{.time}}\",        \"Application\" :
          \"Sampleapp-Staging\"              },      \"dataPoints\" : [[
          {{.time}}, {{.data.evaluation.score}} ]]                  }  ]}'
          https://ozw11698.live.dynatrace.com/api/v1/entity/infrastructure/cust\
          om/custom:releaseevaluationscore"
      subscriptionID: 7211328b-9c02-405e-b7e2-17263ea634c6
      sendFinished: false
